version: "3.8"

services:
  backend:
    build: .
    container_name: backend-polvinho
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - mongo
    command: npm run start

  mongo:
    image: mongo:7.0
    container_name: mongodb-polvinho
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
